apiVersion: v1
kind: Service
metadata:
  name: plantation-app
  namespace: plantation
spec:
  type: NodePort
  selector:
    app: plantation-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
