apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plantation-app-ingress
  namespace: plantation
spec:
  rules:
  - host: plantation.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plantation-app
            port:
              number: 80
